name: Security-Check-Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Vulnerability Check (Task 2)
        # This will fail because of the lodash version
        run: npm audit --audit-level=high

      - name: Secret Leak Check (Task 2)
        # This will fail because of the AKIA key in app.js
        run: |
          if grep -q "AKIA" app.js; then
            echo "SECRET DETECTED! Failing build for security."
            exit 1
          fi
